replicas: 1

args:
  - --kubelet-insecure-tls

podDisruptionBudget:
  enabled: false

nodeSelector:
  node-role.kubernetes.io/worker: ""

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 256Mi
